#!/bin/bash -l
#SBATCH --job-name=my-matlab
#SBATCH -N 1
#SBATCH --ntasks-per-node=1
#SBATCH --partition=shared
#SBATCH --time=6:00:00
#SBATCH --mail-type=end
#SBATCH --mail-user=yjiang48@jhu.edu


##!/bin/bash                                   
##PBS -S /bin/bash       
##PBS -o stdout_file
##PBS -e stderr_file                     
##PBS -l walltime=095:55:59,nodes=1:ppn=4   
##PBS -m abe 
##PBS -M yjjiangphysics@gmail.com 
##PBS -N BDG1

module load matlab 
#matlab -nodisplay -singleCompThread -r "Yi_BDG3; exit"

matlab -nodisplay  -r "Yi_BDG3; exit";
myfile=*.fig; 
if [ ! -f "$myFile" ]; then s=2;cd ..; sed -n '/U_Disorder=/p' vars.m>>../../finished.txt;cd -; fi

#module load git;
#git add *.fig *mat
#git commit -a -m "commit figures"
